language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"
  matrix:
    - DB="POSTGRESQL"
    - DB="MYSQL"

sudo: false

addons:
  apt:
    packages:
      - ldap-utils
      - postfix
      - slapd

cache: pip

services:
  - postgres
  - mysql

before_install:
  - pip install codecov
  - if [[ $DB = "POSTGRESQL" ]]; then pip install -q psycopg2; fi
  - if [[ $DB = "MYSQL" ]]; then pip install -q mysqlclient; fi

install:
  - pip install -q -r requirements.txt
  - pip install -q -r ldap-requirements.txt
  - pip install -q -r test-requirements.txt
  - python setup.py -q develop

before_script:
  - if [[ $DB = "POSTGRESQL" ]]; then psql -c "CREATE DATABASE modoboa_test;" -U postgres; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS modoboa_test;" -uroot; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot; fi
  - if [[ $DB = "MYSQL" ]]; then mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot; fi
  - mkdir /tmp/slapd
  - slapd -f test_data/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f test_data/base.ldif

script:
  - python ./tests.py
  - cd test_project
  - coverage run --source ../modoboa manage.py test modoboa.core modoboa.lib modoboa.admin modoboa.limits modoboa.transport modoboa.relaydomains

after_success:
  - codecov
